"""empty message

Revision ID: 695fef6db344
Revises: 7bbf0815db58
Create Date: 2021-04-24 03:04:05.054277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695fef6db344'
down_revision = '7bbf0815db58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
